# Generated by Django 5.0.7 on 2024-07-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
